feat: Initial E2E framework and simple tests
argoproj-labs/argocd-agent pull request #211
Opened 2024-10-30 18:20 UTC by jopit

Initial E2E framework and simple tests

2024-10-31 11:38 UTC, jannfis approved these changes
LGTM

2024-11-04 12:01 UTC, jgwest requested changes
Looks great, very nice, thanks @jopit! I added some minor comments I noticed while reading through the code, let me know what you think.

I had a couple of questions but they are more general project questions for everyone, so I will loop in Jann et al.

One other question from me:			

Any changes in 'argocd-agent/test/e2e2' that you would suggest we may want to port back to 'argocd-agent/hack/demo-env'?
- For example, extra timeout logic in 'setup-vcluster-env.sh' looked useful for both
- Removal of `.data` from Secrets defined in `argocd-secret.yaml` et al

2024-11-04 12:01 UTC, jgwest commented on Makefile
> +.PHONY: start-argocd-agent
Re: the `Makefile` target of `start-argocd-agent`. Rather than `start-argocd-agent`, which might imply this would start Argo agent for development purposes (similar to `make start` from Argo CD), WDYT about:
- `start-argocd-agent-for-e2e`  (maybe too long?) 
- `start-e2e` / `start-e2e2` (shorter, this is what we use in argo cd, and in rollouts operator)
- Other options?

2024-11-04 12:01 UTC, jgwest commented on test/e2e2/fixture/kubeclient.go
> +type KubeObject interface {
Could add a comment here for `KubeObject` and `KubeObjectList` indicating these are similar to `Object` and `ObjectList` from controller-runtime, or even more generally that this package aims to provide a similar style interface to controller-runtime (which we are avoiding adding a dependency on here).

IMHO this might be useful comment to add (and presuming my assumption is true), but it's up to you!

2024-11-04 12:01 UTC, jgwest commented on test/e2e2/basic_test.go
> +
Can we check that the content (`.spec` field)  is the same between the managed-agent and principal, as well? It's very likely, but it can't hurt to check.

2024-11-04 12:01 UTC, jgwest commented on test/e2e2/basic_test.go
> +	// Delete the app from the principal
Let me know if you think this is scope creep from the original requirements, but before we delete the Application in the next step, can we test the update case, as well? 

E.g. just making a small change to one of the fields of the Application on principal, and making sure it percolates down to managed-agent.

2024-11-04 12:01 UTC, jgwest commented on test/e2e2/basic_test.go
> +
Same as above, can be useful to check `.spec` is in sync, and to test the update case before deleting.

2024-11-04 12:01 UTC, jgwest commented on test/e2e2/fixture/fixture.go
> +	suite.Assert().Nil(err)
Perhaps, `Require` rather than `Assert`? I presume we would want to fail fast if initial cleanup didn't succeed.

2024-11-04 12:01 UTC, jgwest commented on test/e2e2/fixture/kubeconfig.go
> +	}
I think we can remove this `setRateLimitOnRestConfig` part of the function below: if I'm not mistaken the `QPS`/`Burst` values came from managed-gitops, where it made slightly more sense to have a generous rate limit (since managed-gitops was a managed service). But as part of an E2E test, I don't think it's needed (and probably could also have been removed from managed-gitops E2E test setup code as well, for the same reason)

2024-11-04 12:01 UTC, jgwest commented on test/e2e2/fixture_test.go
> +type FixtureTestSuite struct {
Could add a comment like `'FixtureTestSuite' is a set of tests to verify that the E2E test fixture code itself is working as designed, rather than testing the project's components.` Perhaps the comment is too obvious, and thus unnecessary, up to you if you want to add.

2024-11-04 12:01 UTC, jgwest commented on test/e2e2/sync_test.go
> +
As mentioned elsewhere, can be useful to verify that the `.Spec` fields are the same in both places.

2024-11-04 12:01 UTC, jgwest commented on test/e2e2/sync_test.go
> +
As above, couldn't hurt to verify `.spec`s are the same.

2024-11-04 12:01 UTC, jgwest commented on test/e2e2/test-env/start-agent-autonomous.sh
> +test -f cmd/agent/main.go || (echo "Script should be run from argocd-agent's root path" >&2; exit 1)
Rather than testing that the script is run from the correct place, would it be preferable to just add `cd $SCRIPTPATH/../../..` before `go run` to ensure that this is always true?

2024-11-04 12:01 UTC, jgwest commented on test/e2e2/test-env/start-agent-managed.sh
> +test -f cmd/agent/main.go || (echo "Script should be run from argocd-agent's root path" >&2; exit 1)
Same as automonous above, can use SCRIPTPATH if it makes sense.

2024-11-04 12:01 UTC, jgwest commented on test/e2e2/test-env/start-principal.sh
> +test -f cmd/principal/main.go || (echo "Script should be run from argocd-agent's root path" >&2; exit 1)
Same as autonomous above, can use SCRIPTPATH if it makes sense.

2024-11-05 18:38 UTC, jopit commented on Makefile
> +.PHONY: start-argocd-agent
Done. Changed it to `start-e2e2`

2024-11-05 18:38 UTC, jopit commented on test/e2e2/fixture/kubeclient.go
> +type KubeObject interface {
Done.

2024-11-05 18:38 UTC, jopit commented on test/e2e2/basic_test.go
> +
Done.

2024-11-05 18:38 UTC, jopit commented on test/e2e2/basic_test.go
> +	// Delete the app from the principal
Done.

2024-11-05 18:38 UTC, jopit commented on test/e2e2/basic_test.go
> +
Done.

2024-11-05 18:39 UTC, jopit commented on test/e2e2/fixture/fixture.go
> +	suite.Assert().Nil(err)
Done.

2024-11-05 18:39 UTC, jopit commented on test/e2e2/fixture/kubeconfig.go
> +	}
Done.

2024-11-05 18:39 UTC, jopit commented on test/e2e2/fixture_test.go
> +type FixtureTestSuite struct {
Done.

2024-11-05 18:39 UTC, jopit commented on test/e2e2/sync_test.go
> +
Done.

2024-11-05 18:39 UTC, jopit commented on test/e2e2/sync_test.go
> +
Done.

2024-11-05 18:42 UTC, jopit commented on test/e2e2/test-env/start-agent-autonomous.sh
> +test -f cmd/agent/main.go || (echo "Script should be run from argocd-agent's root path" >&2; exit 1)
Resolved this by making the same changes that Jann made to the demo-env scripts to allow running from anywhere in the repo tree, PR #193

2024-11-05 18:42 UTC, jopit commented on test/e2e2/test-env/start-agent-managed.sh
> +test -f cmd/agent/main.go || (echo "Script should be run from argocd-agent's root path" >&2; exit 1)
Resolved this by making the same changes that Jann made to the demo-env scripts to allow running from anywhere in the repo tree, PR #193

2024-11-05 18:42 UTC, jopit commented on test/e2e2/test-env/start-principal.sh
> +test -f cmd/principal/main.go || (echo "Script should be run from argocd-agent's root path" >&2; exit 1)
Resolved this by making the same changes that Jann made to the demo-env scripts to allow running from anywhere in the repo tree, PR #193

2024-11-18 11:46 UTC, jgwest approved these changes
LGTM too, thanks @jopit!

2024-11-18 11:46 UTC, merged