feat: New checkpoint module
argoproj-labs/argocd-agent pull request #222
Opened 2024-11-14 17:26 UTC by jannfis

This adds a new utility module for measuring time by defining checkpoints.

I plan to use this throughout the code for logging and metrics purposes.

2024-11-19 12:00 UTC, jgwest requested changes

2024-11-19 12:00 UTC, jgwest commented on internal/checkpoint/checkpoint.go
> +	return cp.steps
Rather than returning `cp.steps`, should we instead clone the slice (inside the mutex) and return that? 

e.g.
```go
cp.mutex.RLock()
defer cp.mutex.RUnlock()
return append([]Step{}, cp.steps)
```

My concern is that modifications (addition/removal) to the list returned by `Steps()` by the caller (unprotected by mutex), may modify the original list (protected by mutex).

2024-11-19 19:46 UTC, jannfis commented on internal/checkpoint/checkpoint.go
> +	return cp.steps
Great catch!

2024-11-19 19:48 UTC, jannfis commented on internal/checkpoint/checkpoint.go
> +	return cp.steps
```suggestion
	return append([]Step{}, cp.steps...)
```

2024-11-20 04:49 UTC, ishitasequeira approved these changes
LGTM!!

2024-11-20 10:02 UTC, jgwest approved these changes
LGTM, thanks @jannfis!

2024-11-20 12:48 UTC, merged